name: Ci
on: [push,workflow_dispatch]
jobs:
    node-js-ci:
        runs-on: ubuntu-latest
        steps:
            - name: "copy code to server"
              uses: actions/checkout@v4
              
            - name: "use node version"
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: "install dependency"
              run: npm install
            - name: "run the file"
              run: npm run build
